### ISSUE TITLE
dt passed to update is not affected by timescale

### ISSUE THREAD

**Issue by buckle2000** [bjornswenson/lovestep#1]
https://github.com/buckle2000/tick/blob/master/tick.lua#L45

**Comment by bjornbytes** [comment]
Currently, setting `tick.timescale` to 2 only affects the `dt` internal to the library.  This means that `love.update` will be called twice as often but with the same fixed `dt` value.  So I don't think it's correct to also double the `dt` value, otherwise the game would simulate 4 times faster instead of 2.

**Comment by buckle2000** [comment]
Yes, I see.
